/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "e-commerce-msa"
include(":eureka-server")
include(":notification-service")
include(":order-service")
include(":product-service")
include(":inventory-service")
include(":api-gateway")
