server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri= http://keycloak:8181/realms/spring-boot-microservices-realm
management.zipkin.tracing.endpoint=http://zipkin:9411
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761
#app.eureka-server=eureka-server