version: '3.8'
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    restart: always

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    ports:
#      - '1200:8080'
#      image: lscr.io/linuxserver/mysql-workbench:latest
#      container_name: mysql-workbench
#      environment:
#        - PUID=1000
#        - PGID=1000
#        - TZ=Etc/UTC
#      ports:
#        - '3000:3000'
#        - '3001:3001'
#      restart: unless-stopped

volumes:
  mysql-data:
